Add workflows for PRs and releases
FloppyPunk/fp93 pull request #2
Opened 2021-03-17 20:56 UTC by ChrisLGardner

2021-03-17 20:59 UTC, ChrisLGardner commented
The release one isn't quite right yet, just need to figure out the right trigger for it.

2021-03-17 21:07 UTC, ChrisLGardner commented
That should fix it now.

2021-03-19 12:05 UTC, michaeltlombardi commented on .github/workflows/release.yml
> +        GOARCH: amd64
It looks to me like these names are backwards?

2021-03-19 12:05 UTC, michaeltlombardi requested changes
Looks like two of the jobs are mis-named - I think we also wanna build release binaries for MacOS

2021-03-19 12:33 UTC, ChrisLGardner commented
Copy and paste got me there. I'll get that fixed and add Mac too. I'd left it off initially as I didn't see support for it in upx but might have overlooked it, though its probably worth building them anyway and letting people get them from github if needed.

2021-03-23 01:55 UTC, michaeltlombardi approved these changes

2021-03-23 01:55 UTC, merged